spring:
  datasource:
    url: jdbc:${DB_HOST}:${DB_NAME};MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: ${DB_USER}
    password: ${DB_PSWD}
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
